// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Black_Chair = "Black Chair",
  Black_Chair_2 = "Black Chair_2",
  Black_Chair_3 = "Black Chair_3",
  Black_Chair_4 = "Black Chair_4",
  Black_Chair_5 = "Black Chair_5",
  Black_Chair_6 = "Black Chair_6",
  Black_Chair_7 = "Black Chair_7",
  Black_Chair_8 = "Black Chair_8",
  Doorframe___HorizontalBoard = "Doorframe - HorizontalBoard",
  Image = "Image",
  Image_2 = "Image_2",
  Image_2_10 = "Image_2_10",
  Image_2_11 = "Image_2_11",
  Image_2_3 = "Image_2_3",
  Image_2_4 = "Image_2_4",
  Image_2_5 = "Image_2_5",
  Image_2_6 = "Image_2_6",
  Image_2_7 = "Image_2_7",
  Image_2_8 = "Image_2_8",
  Image_2_9 = "Image_2_9",
  Point_light = "Point light",
  Roof___White = "Roof - White",
  Sidewalk_Tile = "Sidewalk Tile",
  Sidewalk_Tile_2 = "Sidewalk Tile_2",
  Sidewalk_Tile_3 = "Sidewalk Tile_3",
  Sidewalk_Tile_4 = "Sidewalk Tile_4",
  Sidewalk_Tile_5 = "Sidewalk Tile_5",
  Sidewalk_Tile_6 = "Sidewalk Tile_6",
  Sidewalk_Tile_7 = "Sidewalk Tile_7",
  Sidewalk_Tile_8 = "Sidewalk Tile_8",
  Sidewalk_Tile_9 = "Sidewalk Tile_9",
  Sit_Spot = "Sit Spot",
  Sit_Spot_2 = "Sit Spot_2",
  Sit_Spot_3 = "Sit Spot_3",
  Sit_Spot_4 = "Sit Spot_4",
  Sit_Spot_5 = "Sit Spot_5",
  Sit_Spot_6 = "Sit Spot_6",
  Sit_Spot_7 = "Sit Spot_7",
  Sit_Spot_8 = "Sit Spot_8",
  Text = "Text",
  Text_10 = "Text_10",
  Text_11 = "Text_11",
  Text_12 = "Text_12",
  Text_13 = "Text_13",
  Text_14 = "Text_14",
  Text_15 = "Text_15",
  Text_16 = "Text_16",
  Text_17 = "Text_17",
  Text_2 = "Text_2",
  Text_3 = "Text_3",
  Text_4 = "Text_4",
  Text_5 = "Text_5",
  Text_6 = "Text_6",
  Text_7 = "Text_7",
  Text_8 = "Text_8",
  Text_9 = "Text_9",
  Wall___HorizontalBoard = "Wall - HorizontalBoard",
  Wall___HorizontalBoard_10 = "Wall - HorizontalBoard_10",
  Wall___HorizontalBoard_11 = "Wall - HorizontalBoard_11",
  Wall___HorizontalBoard_12 = "Wall - HorizontalBoard_12",
  Wall___HorizontalBoard_13 = "Wall - HorizontalBoard_13",
  Wall___HorizontalBoard_14 = "Wall - HorizontalBoard_14",
  Wall___HorizontalBoard_15 = "Wall - HorizontalBoard_15",
  Wall___HorizontalBoard_16 = "Wall - HorizontalBoard_16",
  Wall___HorizontalBoard_17 = "Wall - HorizontalBoard_17",
  Wall___HorizontalBoard_18 = "Wall - HorizontalBoard_18",
  Wall___HorizontalBoard_19 = "Wall - HorizontalBoard_19",
  Wall___HorizontalBoard_2 = "Wall - HorizontalBoard_2",
  Wall___HorizontalBoard_20 = "Wall - HorizontalBoard_20",
  Wall___HorizontalBoard_3 = "Wall - HorizontalBoard_3",
  Wall___HorizontalBoard_4 = "Wall - HorizontalBoard_4",
  Wall___HorizontalBoard_5 = "Wall - HorizontalBoard_5",
  Wall___HorizontalBoard_6 = "Wall - HorizontalBoard_6",
  Wall___HorizontalBoard_7 = "Wall - HorizontalBoard_7",
  Wall___HorizontalBoard_8 = "Wall - HorizontalBoard_8",
  Wall___HorizontalBoard_9 = "Wall - HorizontalBoard_9",
  Wall___PlainBlack = "Wall - PlainBlack",
  Wall___PlainWhite = "Wall - PlainWhite",
  Wooden_Door = "Wooden Door",
} 
