export type InterClassScenarioAnswer = 'stable-positive' | 'sudden-drop' | 'gradual-improvement' | 'polarized' | 'unclear'
export type InterClassAnomalyAnswer = 'none' | 'early' | 'middle' | 'late'

export type InterClassDataPoint = {
  id: number
  value: number
  labels: string[]
}

export type InterClassScenarioDefinition = {
  scenarioId: string
  scenarioLabel: string
  description: string
  expectedAnswer: InterClassScenarioAnswer
  expectedAnomaly: InterClassAnomalyAnswer
  anomalyDescription: string
  data: InterClassDataPoint[]
}

type InterClassRawPoint = {
  value: number
  positive: number
  neutral: number
  negative: number
}

function makeLabels(positive: number, neutral: number, negative: number): string[] {
  const labels: string[] = []

  for (let i = 0; i < positive; i++) labels.push('positive')
  for (let i = 0; i < neutral; i++) labels.push('neutral')
  for (let i = 0; i < negative; i++) labels.push('negative')

  return labels
}

function makeData(points: InterClassRawPoint[]): InterClassDataPoint[] {
  return points.map((point, index) => ({
    id: index + 1,
    value: point.value,
    labels: makeLabels(point.positive, point.neutral, point.negative),
  }))
}

function withPointOverrides(
  points: InterClassRawPoint[],
  overrides: Record<number, InterClassRawPoint>
): InterClassRawPoint[] {
  return points.map((point, index) => overrides[index + 1] ?? point)
}

const STABLE_POSITIVE_POINTS: InterClassRawPoint[] = [
  { value: 7.8, positive: 9, neutral: 1, negative: 3 },
  { value: 7.6, positive: 12, neutral: 2, negative: 4 },
  { value: 7.8, positive: 8, neutral: 1, negative: 2 },
  { value: 7.9, positive: 12, neutral: 1, negative: 4 },
  { value: 8.1, positive: 9, neutral: 1, negative: 3 },
  { value: 8.1, positive: 11, neutral: 1, negative: 4 },
  { value: 8.1, positive: 6, neutral: 2, negative: 1 },
  { value: 7.6, positive: 12, neutral: 3, negative: 3 },
  { value: 7.7, positive: 10, neutral: 1, negative: 3 },
  { value: 7.3, positive: 8, neutral: 1, negative: 3 },
  { value: 7.3, positive: 6, neutral: 0, negative: 2 },
  { value: 7.4, positive: 11, neutral: 1, negative: 4 },
  { value: 7.1, positive: 8, neutral: 2, negative: 3 },
  { value: 7.1, positive: 9, neutral: 1, negative: 5 },
  { value: 7.4, positive: 8, neutral: 1, negative: 3 },
  { value: 7.4, positive: 11, neutral: 1, negative: 4 },
  { value: 7.3, positive: 8, neutral: 1, negative: 3 },
  { value: 7.6, positive: 7, neutral: 1, negative: 3 },
  { value: 7.8, positive: 11, neutral: 1, negative: 4 },
  { value: 7.5, positive: 5, neutral: 1, negative: 2 },
  { value: 8.0, positive: 6, neutral: 1, negative: 2 },
  { value: 8.1, positive: 8, neutral: 2, negative: 2 },
  { value: 7.9, positive: 13, neutral: 2, negative: 2 },
  { value: 7.8, positive: 10, neutral: 1, negative: 4 },
  { value: 8.2, positive: 12, neutral: 2, negative: 2 },
  { value: 7.8, positive: 11, neutral: 2, negative: 2 },
  { value: 7.6, positive: 11, neutral: 2, negative: 3 },
  { value: 7.5, positive: 7, neutral: 1, negative: 3 },
  { value: 7.7, positive: 8, neutral: 1, negative: 2 },
  { value: 7.5, positive: 13, neutral: 1, negative: 4 },
  { value: 7.5, positive: 11, neutral: 2, negative: 3 },
  { value: 7.4, positive: 6, neutral: 1, negative: 2 },
  { value: 7.3, positive: 7, neutral: 2, negative: 2 },
  { value: 7.6, positive: 11, neutral: 4, negative: 3 },
  { value: 7.3, positive: 6, neutral: 1, negative: 1 },
  { value: 7.5, positive: 7, neutral: 1, negative: 3 },
  { value: 6.4, positive: 8, neutral: 1, negative: 4 },
  { value: 5.0, positive: 3, neutral: 6, negative: 7 },
  { value: 3.8, positive: 2, neutral: 3, negative: 9 },
  { value: 3.1, positive: 2, neutral: 3, negative: 11 },
  { value: 3.4, positive: 3, neutral: 2, negative: 11 },
  { value: 4.1, positive: 4, neutral: 3, negative: 11 },
  { value: 5.5, positive: 8, neutral: 1, negative: 6 },
  { value: 6.7, positive: 8, neutral: 1, negative: 4 },
  { value: 7.6, positive: 7, neutral: 1, negative: 2 },
  { value: 7.5, positive: 8, neutral: 1, negative: 2 },
  { value: 7.7, positive: 10, neutral: 2, negative: 4 },
  { value: 7.6, positive: 11, neutral: 1, negative: 4 },
  { value: 7.8, positive: 7, neutral: 2, negative: 2 },
  { value: 7.5, positive: 7, neutral: 1, negative: 3 },
  { value: 7.7, positive: 6, neutral: 1, negative: 3 },
  { value: 7.8, positive: 8, neutral: 1, negative: 3 },
  { value: 7.7, positive: 8, neutral: 1, negative: 3 },
  { value: 7.9, positive: 11, neutral: 2, negative: 3 },
  { value: 7.8, positive: 7, neutral: 1, negative: 3 },
  { value: 8.0, positive: 13, neutral: 2, negative: 2 },
  { value: 8.1, positive: 9, neutral: 1, negative: 3 },
  { value: 8.0, positive: 12, neutral: 1, negative: 3 },
  { value: 7.9, positive: 6, neutral: 1, negative: 1 },
  { value: 7.8, positive: 6, neutral: 3, negative: 1 },
  { value: 7.8, positive: 7, neutral: 1, negative: 3 },
  { value: 8.0, positive: 12, neutral: 1, negative: 4 },
  { value: 7.8, positive: 11, neutral: 2, negative: 4 },
  { value: 7.7, positive: 11, neutral: 1, negative: 5 },
  { value: 7.4, positive: 8, neutral: 1, negative: 2 },
  { value: 7.6, positive: 8, neutral: 1, negative: 3 },
  { value: 7.3, positive: 7, neutral: 1, negative: 4 },
  { value: 7.4, positive: 5, neutral: 2, negative: 2 },
  { value: 7.7, positive: 13, neutral: 1, negative: 3 },
  { value: 7.5, positive: 8, neutral: 1, negative: 2 },
  { value: 7.5, positive: 9, neutral: 1, negative: 3 },
  { value: 7.6, positive: 9, neutral: 1, negative: 3 },
  { value: 7.7, positive: 11, neutral: 1, negative: 4 },
  { value: 7.8, positive: 12, neutral: 2, negative: 4 },
  { value: 7.6, positive: 11, neutral: 1, negative: 4 },
  { value: 7.6, positive: 6, neutral: 1, negative: 3 },
  { value: 7.8, positive: 10, neutral: 3, negative: 3 },
  { value: 7.8, positive: 8, neutral: 1, negative: 2 },
  { value: 7.9, positive: 13, neutral: 1, negative: 4 },
  { value: 8.3, positive: 9, neutral: 0, negative: 3 }
]

const SUDDEN_DROP_POINTS: InterClassRawPoint[] = [
  { value: 7.3, positive: 10, neutral: 1, negative: 5 },
  { value: 7.6, positive: 12, neutral: 2, negative: 4 },
  { value: 7.6, positive: 13, neutral: 1, negative: 4 },
  { value: 7.5, positive: 12, neutral: 1, negative: 5 },
  { value: 8.0, positive: 8, neutral: 1, negative: 3 },
  { value: 8.0, positive: 9, neutral: 2, negative: 2 },
  { value: 7.8, positive: 7, neutral: 1, negative: 2 },
  { value: 8.0, positive: 10, neutral: 1, negative: 3 },
  { value: 7.9, positive: 12, neutral: 2, negative: 3 },
  { value: 7.8, positive: 5, neutral: 2, negative: 1 },
  { value: 7.5, positive: 12, neutral: 1, negative: 4 },
  { value: 7.4, positive: 10, neutral: 2, negative: 3 },
  { value: 7.8, positive: 10, neutral: 1, negative: 4 },
  { value: 7.8, positive: 7, neutral: 1, negative: 2 },
  { value: 7.5, positive: 13, neutral: 1, negative: 4 },
  { value: 7.5, positive: 8, neutral: 1, negative: 2 },
  { value: 7.3, positive: 7, neutral: 2, negative: 2 },
  { value: 7.0, positive: 9, neutral: 1, negative: 5 },
  { value: 6.9, positive: 9, neutral: 1, negative: 5 },
  { value: 7.0, positive: 7, neutral: 1, negative: 3 },
  { value: 7.3, positive: 9, neutral: 1, negative: 4 },
  { value: 7.3, positive: 5, neutral: 1, negative: 2 },
  { value: 7.3, positive: 6, neutral: 1, negative: 2 },
  { value: 7.4, positive: 11, neutral: 1, negative: 4 },
  { value: 7.1, positive: 6, neutral: 0, negative: 3 },
  { value: 7.2, positive: 12, neutral: 1, negative: 5 },
  { value: 7.1, positive: 8, neutral: 1, negative: 4 },
  { value: 7.6, positive: 11, neutral: 1, negative: 5 },
  { value: 7.8, positive: 10, neutral: 1, negative: 3 },
  { value: 7.6, positive: 7, neutral: 1, negative: 2 },
  { value: 7.8, positive: 8, neutral: 1, negative: 3 },
  { value: 7.6, positive: 8, neutral: 1, negative: 3 },
  { value: 8.1, positive: 12, neutral: 3, negative: 3 },
  { value: 8.1, positive: 8, neutral: 2, negative: 2 },
  { value: 8.2, positive: 11, neutral: 3, negative: 2 },
  { value: 6.9, positive: 9, neutral: 1, negative: 4 },
  { value: 6.3, positive: 5, neutral: 1, negative: 3 },
  { value: 5.5, positive: 8, neutral: 2, negative: 5 },
  { value: 5.0, positive: 7, neutral: 1, negative: 6 },
  { value: 4.0, positive: 3, neutral: 1, negative: 4 },
  { value: 3.3, positive: 5, neutral: 1, negative: 8 },
  { value: 2.9, positive: 4, neutral: 1, negative: 7 },
  { value: 2.5, positive: 4, neutral: 1, negative: 9 },
  { value: 2.2, positive: 6, neutral: 1, negative: 10 },
  { value: 2.2, positive: 3, neutral: 2, negative: 7 },
  { value: 2.6, positive: 4, neutral: 1, negative: 8 },
  { value: 2.5, positive: 3, neutral: 1, negative: 6 },
  { value: 3.0, positive: 6, neutral: 1, negative: 10 },
  { value: 2.9, positive: 6, neutral: 3, negative: 8 },
  { value: 2.4, positive: 5, neutral: 1, negative: 12 },
  { value: 2.7, positive: 3, neutral: 1, negative: 6 },
  { value: 2.4, positive: 3, neutral: 2, negative: 6 },
  { value: 2.2, positive: 3, neutral: 2, negative: 9 },
  { value: 2.6, positive: 4, neutral: 3, negative: 7 },
  { value: 2.2, positive: 3, neutral: 1, negative: 4 },
  { value: 2.0, positive: 3, neutral: 3, negative: 7 },
  { value: 2.2, positive: 4, neutral: 4, negative: 10 },
  { value: 3.3, positive: 4, neutral: 2, negative: 5 },
  { value: 2.8, positive: 3, neutral: 1, negative: 6 },
  { value: 2.4, positive: 3, neutral: 1, negative: 5 },
  { value: 2.7, positive: 4, neutral: 2, negative: 6 },
  { value: 2.7, positive: 6, neutral: 1, negative: 10 },
  { value: 3.2, positive: 4, neutral: 1, negative: 5 },
  { value: 2.9, positive: 3, neutral: 1, negative: 4 },
  { value: 4.0, positive: 6, neutral: 1, negative: 7 },
  { value: 3.4, positive: 3, neutral: 1, negative: 5 },
  { value: 2.9, positive: 3, neutral: 1, negative: 7 },
  { value: 3.5, positive: 7, neutral: 3, negative: 8 },
  { value: 3.1, positive: 7, neutral: 1, negative: 9 },
  { value: 3.0, positive: 5, neutral: 2, negative: 7 },
  { value: 3.2, positive: 6, neutral: 1, negative: 11 },
  { value: 3.4, positive: 5, neutral: 1, negative: 9 },
  { value: 4.0, positive: 8, neutral: 2, negative: 8 },
  { value: 3.2, positive: 3, neutral: 1, negative: 6 },
  { value: 3.0, positive: 6, neutral: 1, negative: 11 },
  { value: 3.1, positive: 6, neutral: 1, negative: 9 },
  { value: 2.8, positive: 5, neutral: 1, negative: 11 },
  { value: 3.0, positive: 3, neutral: 1, negative: 5 },
  { value: 2.4, positive: 5, neutral: 1, negative: 9 },
  { value: 3.0, positive: 4, neutral: 1, negative: 8 }
]

const GRADUAL_IMPROVEMENT_POINTS: InterClassRawPoint[] = [
  { value: 2.3, positive: 6, neutral: 1, negative: 10 },
  { value: 2.4, positive: 4, neutral: 1, negative: 12 },
  { value: 2.9, positive: 4, neutral: 0, negative: 5 },
  { value: 2.8, positive: 3, neutral: 2, negative: 6 },
  { value: 3.2, positive: 3, neutral: 3, negative: 5 },
  { value: 3.2, positive: 3, neutral: 0, negative: 5 },
  { value: 3.0, positive: 5, neutral: 2, negative: 8 },
  { value: 2.9, positive: 4, neutral: 1, negative: 7 },
  { value: 3.6, positive: 6, neutral: 3, negative: 9 },
  { value: 3.1, positive: 6, neutral: 2, negative: 10 },
  { value: 3.5, positive: 4, neutral: 1, negative: 6 },
  { value: 3.4, positive: 6, neutral: 3, negative: 9 },
  { value: 3.6, positive: 3, neutral: 2, negative: 5 },
  { value: 3.6, positive: 5, neutral: 1, negative: 6 },
  { value: 3.5, positive: 4, neutral: 2, negative: 6 },
  { value: 3.4, positive: 4, neutral: 1, negative: 7 },
  { value: 3.6, positive: 6, neutral: 2, negative: 8 },
  { value: 3.2, positive: 5, neutral: 3, negative: 9 },
  { value: 3.3, positive: 5, neutral: 2, negative: 6 },
  { value: 3.6, positive: 5, neutral: 0, negative: 6 },
  { value: 3.4, positive: 7, neutral: 2, negative: 8 },
  { value: 3.6, positive: 8, neutral: 1, negative: 9 },
  { value: 3.6, positive: 4, neutral: 1, negative: 5 },
  { value: 3.6, positive: 4, neutral: 2, negative: 6 },
  { value: 3.1, positive: 7, neutral: 1, negative: 10 },
  { value: 3.4, positive: 5, neutral: 2, negative: 8 },
  { value: 3.2, positive: 5, neutral: 4, negative: 9 },
  { value: 4.1, positive: 6, neutral: 2, negative: 6 },
  { value: 3.9, positive: 6, neutral: 1, negative: 7 },
  { value: 4.1, positive: 5, neutral: 3, negative: 7 },
  { value: 4.1, positive: 4, neutral: 1, negative: 4 },
  { value: 4.3, positive: 8, neutral: 2, negative: 6 },
  { value: 4.4, positive: 7, neutral: 3, negative: 6 },
  { value: 4.8, positive: 7, neutral: 1, negative: 8 },
  { value: 5.0, positive: 9, neutral: 3, negative: 6 },
  { value: 4.8, positive: 5, neutral: 1, negative: 6 },
  { value: 4.9, positive: 8, neutral: 1, negative: 6 },
  { value: 5.2, positive: 4, neutral: 1, negative: 3 },
  { value: 5.5, positive: 6, neutral: 1, negative: 4 },
  { value: 5.7, positive: 4, neutral: 2, negative: 2 },
  { value: 5.5, positive: 5, neutral: 1, negative: 3 },
  { value: 5.4, positive: 5, neutral: 1, negative: 4 },
  { value: 5.4, positive: 9, neutral: 1, negative: 6 },
  { value: 5.4, positive: 9, neutral: 1, negative: 5 },
  { value: 5.5, positive: 8, neutral: 3, negative: 5 },
  { value: 5.5, positive: 9, neutral: 1, negative: 7 },
  { value: 5.4, positive: 4, neutral: 1, negative: 4 },
  { value: 5.7, positive: 7, neutral: 1, negative: 6 },
  { value: 5.5, positive: 7, neutral: 1, negative: 4 },
  { value: 6.0, positive: 7, neutral: 1, negative: 4 },
  { value: 5.7, positive: 10, neutral: 2, negative: 6 },
  { value: 5.8, positive: 9, neutral: 2, negative: 5 },
  { value: 5.1, positive: 7, neutral: 2, negative: 7 },
  { value: 5.6, positive: 7, neutral: 0, negative: 4 },
  { value: 5.8, positive: 7, neutral: 1, negative: 6 },
  { value: 6.0, positive: 4, neutral: 1, negative: 3 },
  { value: 5.9, positive: 8, neutral: 1, negative: 5 },
  { value: 5.9, positive: 11, neutral: 1, negative: 6 },
  { value: 6.0, positive: 4, neutral: 1, negative: 3 },
  { value: 5.9, positive: 7, neutral: 1, negative: 5 },
  { value: 6.0, positive: 8, neutral: 1, negative: 6 },
  { value: 6.6, positive: 5, neutral: 1, negative: 2 },
  { value: 6.5, positive: 12, neutral: 2, negative: 4 },
  { value: 6.8, positive: 7, neutral: 1, negative: 4 },
  { value: 6.7, positive: 10, neutral: 3, negative: 5 },
  { value: 6.6, positive: 12, neutral: 1, negative: 5 },
  { value: 7.1, positive: 8, neutral: 1, negative: 4 },
  { value: 6.9, positive: 10, neutral: 2, negative: 3 },
  { value: 7.1, positive: 5, neutral: 1, negative: 3 },
  { value: 7.4, positive: 8, neutral: 1, negative: 3 },
  { value: 7.4, positive: 9, neutral: 1, negative: 4 },
  { value: 7.9, positive: 6, neutral: 1, negative: 2 },
  { value: 7.4, positive: 5, neutral: 1, negative: 2 },
  { value: 7.9, positive: 8, neutral: 2, negative: 2 },
  { value: 7.9, positive: 8, neutral: 1, negative: 2 },
  { value: 8.0, positive: 7, neutral: 2, negative: 1 },
  { value: 7.7, positive: 10, neutral: 1, negative: 3 },
  { value: 7.9, positive: 11, neutral: 3, negative: 3 },
  { value: 7.9, positive: 8, neutral: 1, negative: 3 },
  { value: 7.9, positive: 11, neutral: 1, negative: 3 }
]

const POLARIZED_POINTS: InterClassRawPoint[] = [
  { value: 6.0, positive: 3, neutral: 4, negative: 3 },
  { value: 6.6, positive: 7, neutral: 4, negative: 7 },
  { value: 6.8, positive: 3, neutral: 4, negative: 3 },
  { value: 6.4, positive: 6, neutral: 4, negative: 5 },
  { value: 5.9, positive: 6, neutral: 1, negative: 5 },
  { value: 5.9, positive: 3, neutral: 4, negative: 4 },
  { value: 5.4, positive: 3, neutral: 3, negative: 5 },
  { value: 5.4, positive: 7, neutral: 3, negative: 8 },
  { value: 5.4, positive: 6, neutral: 3, negative: 9 },
  { value: 5.1, positive: 5, neutral: 2, negative: 5 },
  { value: 4.8, positive: 7, neutral: 1, negative: 7 },
  { value: 4.2, positive: 6, neutral: 1, negative: 11 },
  { value: 3.9, positive: 5, neutral: 2, negative: 6 },
  { value: 3.4, positive: 5, neutral: 2, negative: 10 },
  { value: 4.0, positive: 6, neutral: 2, negative: 8 },
  { value: 4.5, positive: 4, neutral: 3, negative: 4 },
  { value: 5.9, positive: 7, neutral: 1, negative: 9 },
  { value: 6.9, positive: 4, neutral: 2, negative: 4 },
  { value: 6.1, positive: 5, neutral: 1, negative: 4 },
  { value: 6.4, positive: 3, neutral: 2, negative: 3 },
  { value: 6.1, positive: 3, neutral: 3, negative: 5 },
  { value: 6.1, positive: 5, neutral: 1, negative: 6 },
  { value: 4.9, positive: 6, neutral: 1, negative: 7 },
  { value: 5.3, positive: 6, neutral: 4, negative: 5 },
  { value: 6.1, positive: 7, neutral: 1, negative: 8 },
  { value: 5.9, positive: 5, neutral: 1, negative: 5 },
  { value: 5.5, positive: 7, neutral: 3, negative: 8 },
  { value: 4.9, positive: 4, neutral: 1, negative: 3 },
  { value: 4.1, positive: 4, neutral: 4, negative: 6 },
  { value: 3.7, positive: 4, neutral: 4, negative: 7 },
  { value: 3.5, positive: 2, neutral: 3, negative: 4 },
  { value: 4.0, positive: 3, neutral: 2, negative: 4 },
  { value: 4.5, positive: 6, neutral: 3, negative: 9 },
  { value: 5.8, positive: 7, neutral: 3, negative: 7 },
  { value: 6.6, positive: 6, neutral: 4, negative: 7 },
  { value: 5.7, positive: 3, neutral: 2, negative: 4 },
  { value: 5.7, positive: 3, neutral: 4, negative: 4 },
  { value: 5.9, positive: 5, neutral: 4, negative: 6 },
  { value: 5.7, positive: 3, neutral: 3, negative: 3 },
  { value: 5.9, positive: 7, neutral: 3, negative: 8 },
  { value: 6.4, positive: 3, neutral: 4, negative: 3 },
  { value: 6.7, positive: 4, neutral: 1, negative: 4 },
  { value: 6.2, positive: 6, neutral: 2, negative: 5 },
  { value: 5.8, positive: 7, neutral: 3, negative: 7 },
  { value: 4.9, positive: 6, neutral: 3, negative: 5 },
  { value: 3.0, positive: 6, neutral: 1, negative: 7 },
  { value: 2.7, positive: 5, neutral: 3, negative: 9 },
  { value: 3.7, positive: 5, neutral: 2, negative: 10 },
  { value: 3.9, positive: 6, neutral: 2, negative: 7 },
  { value: 4.3, positive: 4, neutral: 3, negative: 6 },
  { value: 5.9, positive: 5, neutral: 2, negative: 5 },
  { value: 6.4, positive: 8, neutral: 1, negative: 7 },
  { value: 5.5, positive: 6, neutral: 3, negative: 9 },
  { value: 5.6, positive: 5, neutral: 3, negative: 4 },
  { value: 5.8, positive: 5, neutral: 1, negative: 7 },
  { value: 6.1, positive: 3, neutral: 4, negative: 3 },
  { value: 6.3, positive: 7, neutral: 1, negative: 10 },
  { value: 6.9, positive: 7, neutral: 2, negative: 7 },
  { value: 6.5, positive: 5, neutral: 3, negative: 7 },
  { value: 6.3, positive: 5, neutral: 3, negative: 4 },
  { value: 5.5, positive: 9, neutral: 1, negative: 7 },
  { value: 4.8, positive: 4, neutral: 2, negative: 4 },
  { value: 4.1, positive: 3, neutral: 1, negative: 4 },
  { value: 3.8, positive: 6, neutral: 4, negative: 8 },
  { value: 4.0, positive: 4, neutral: 4, negative: 7 },
  { value: 4.4, positive: 6, neutral: 1, negative: 9 },
  { value: 4.4, positive: 3, neutral: 3, negative: 3 },
  { value: 5.2, positive: 6, neutral: 4, negative: 7 },
  { value: 4.9, positive: 4, neutral: 1, negative: 7 },
  { value: 4.1, positive: 5, neutral: 1, negative: 11 },
  { value: 5.1, positive: 5, neutral: 2, negative: 5 },
  { value: 5.6, positive: 4, neutral: 3, negative: 5 },
  { value: 5.9, positive: 2, neutral: 4, negative: 2 },
  { value: 6.6, positive: 4, neutral: 2, negative: 4 },
  { value: 6.8, positive: 4, neutral: 3, negative: 4 },
  { value: 7.1, positive: 2, neutral: 4, negative: 2 },
  { value: 6.2, positive: 3, neutral: 3, negative: 3 },
  { value: 5.5, positive: 7, neutral: 4, negative: 6 },
  { value: 4.6, positive: 4, neutral: 3, negative: 7 },
  { value: 4.5, positive: 2, neutral: 3, negative: 3 }
]


const STABLE_POSITIVE_WITH_ANOMALY_POINTS = STABLE_POSITIVE_POINTS
const STABLE_POSITIVE_NO_ANOMALY_POINTS = withPointOverrides(STABLE_POSITIVE_POINTS, {
  37: { value: 7.4, positive: 9, neutral: 2, negative: 3 },
  38: { value: 7.6, positive: 10, neutral: 2, negative: 3 },
  39: { value: 7.7, positive: 11, neutral: 2, negative: 3 },
  40: { value: 7.8, positive: 10, neutral: 1, negative: 3 },
  41: { value: 7.6, positive: 9, neutral: 2, negative: 3 },
  42: { value: 7.5, positive: 8, neutral: 2, negative: 4 },
  43: { value: 7.7, positive: 10, neutral: 2, negative: 3 },
  44: { value: 7.8, positive: 11, neutral: 1, negative: 3 },
})

const SUDDEN_DROP_NO_ANOMALY_POINTS = SUDDEN_DROP_POINTS
const SUDDEN_DROP_WITH_ANOMALY_POINTS = withPointOverrides(SUDDEN_DROP_POINTS, {
  64: { value: 3.1, positive: 4, neutral: 2, negative: 7 },
  65: { value: 4.0, positive: 6, neutral: 2, negative: 7 },
  66: { value: 6.6, positive: 11, neutral: 3, negative: 4 },
  67: { value: 7.2, positive: 13, neutral: 2, negative: 3 },
  68: { value: 6.8, positive: 10, neutral: 3, negative: 4 },
  69: { value: 3.5, positive: 5, neutral: 2, negative: 8 },
  70: { value: 3.0, positive: 4, neutral: 2, negative: 8 },
})

const GRADUAL_IMPROVEMENT_NO_ANOMALY_POINTS = GRADUAL_IMPROVEMENT_POINTS
const GRADUAL_IMPROVEMENT_WITH_ANOMALY_POINTS = withPointOverrides(GRADUAL_IMPROVEMENT_POINTS, {
  62: { value: 6.4, positive: 8, neutral: 2, negative: 4 },
  63: { value: 6.7, positive: 10, neutral: 2, negative: 4 },
  64: { value: 3.4, positive: 3, neutral: 3, negative: 10 },
  65: { value: 2.8, positive: 2, neutral: 3, negative: 12 },
  66: { value: 3.2, positive: 3, neutral: 2, negative: 11 },
  67: { value: 6.8, positive: 10, neutral: 2, negative: 4 },
  68: { value: 7.2, positive: 12, neutral: 2, negative: 3 },
})

const POLARIZED_NO_ANOMALY_POINTS = POLARIZED_POINTS
const POLARIZED_WITH_ANOMALY_POINTS = withPointOverrides(POLARIZED_POINTS, {
  36: { value: 5.7, positive: 5, neutral: 3, negative: 5 },
  37: { value: 6.1, positive: 6, neutral: 3, negative: 5 },
  38: { value: 8.3, positive: 13, neutral: 2, negative: 2 },
  39: { value: 8.7, positive: 15, neutral: 2, negative: 1 },
  40: { value: 8.5, positive: 14, neutral: 3, negative: 2 },
  41: { value: 6.2, positive: 6, neutral: 4, negative: 5 },
  42: { value: 5.8, positive: 5, neutral: 3, negative: 6 },
})

export const INTER_CLASS_TEST_1_SCENARIOS: InterClassScenarioDefinition[] = [
  {
    scenarioId: 'stable_positive_no_anomaly',
    scenarioLabel: 'Stable positive - no anomaly',
    description: 'Mostly positive and stable conversation, with realistic local fluctuations but no isolated anomaly.',
    expectedAnswer: 'stable-positive',
    expectedAnomaly: 'none',
    anomalyDescription: 'No isolated anomaly; the conversation remains consistently positive with normal fluctuations.',
    data: makeData(STABLE_POSITIVE_NO_ANOMALY_POINTS),
  },
  {
    scenarioId: 'stable_positive_with_anomaly',
    scenarioLabel: 'Stable positive - with anomaly',
    description: 'Mostly positive and stable conversation, with one clearly visible negative incident in the middle.',
    expectedAnswer: 'stable-positive',
    expectedAnomaly: 'middle',
    anomalyDescription: 'A clear negative dip appears in the middle of an otherwise stable positive conversation.',
    data: makeData(STABLE_POSITIVE_WITH_ANOMALY_POINTS),
  },
  {
    scenarioId: 'sudden_drop_no_anomaly',
    scenarioLabel: 'Sudden drop - no anomaly',
    description: 'The conversation starts positively, then sentiment drops and remains mostly negative; the drop is the main pattern, not an isolated anomaly.',
    expectedAnswer: 'sudden-drop',
    expectedAnomaly: 'none',
    anomalyDescription: 'No isolated anomaly; the relevant pattern is a sustained drop from positive to negative sentiment.',
    data: makeData(SUDDEN_DROP_NO_ANOMALY_POINTS),
  },
  {
    scenarioId: 'sudden_drop_with_anomaly',
    scenarioLabel: 'Sudden drop - with anomaly',
    description: 'The conversation starts positively, sentiment collapses, then a short positive rebound appears late as an isolated anomaly.',
    expectedAnswer: 'sudden-drop',
    expectedAnomaly: 'late',
    anomalyDescription: 'A short positive rebound appears late in an otherwise negative final phase.',
    data: makeData(SUDDEN_DROP_WITH_ANOMALY_POINTS),
  },
  {
    scenarioId: 'gradual_improvement_no_anomaly',
    scenarioLabel: 'Gradual improvement - no anomaly',
    description: 'The conversation progressively improves, with realistic local setbacks but no isolated anomaly.',
    expectedAnswer: 'gradual-improvement',
    expectedAnomaly: 'none',
    anomalyDescription: 'No isolated anomaly; the relevant pattern is gradual improvement with normal fluctuations.',
    data: makeData(GRADUAL_IMPROVEMENT_NO_ANOMALY_POINTS),
  },
  {
    scenarioId: 'gradual_improvement_with_anomaly',
    scenarioLabel: 'Gradual improvement - with anomaly',
    description: 'The conversation generally improves, but a clear negative incident appears late after the sentiment has become positive.',
    expectedAnswer: 'gradual-improvement',
    expectedAnomaly: 'late',
    anomalyDescription: 'A clear negative setback appears late, interrupting the otherwise improving trend.',
    data: makeData(GRADUAL_IMPROVEMENT_WITH_ANOMALY_POINTS),
  },
  {
    scenarioId: 'polarized_no_anomaly',
    scenarioLabel: 'Polarized - no anomaly',
    description: 'The conversation is emotionally divided, with many positive and negative messages appearing together throughout.',
    expectedAnswer: 'polarized',
    expectedAnomaly: 'none',
    anomalyDescription: 'No isolated anomaly; the relevant pattern is persistent polarization and disagreement.',
    data: makeData(POLARIZED_NO_ANOMALY_POINTS),
  },
  {
    scenarioId: 'polarized_with_anomaly',
    scenarioLabel: 'Polarized - with anomaly',
    description: 'The conversation is usually polarized, but briefly becomes unusually one-sided and positive in the middle.',
    expectedAnswer: 'polarized',
    expectedAnomaly: 'middle',
    anomalyDescription: 'A short unusually positive consensus appears in the middle of an otherwise polarized conversation.',
    data: makeData(POLARIZED_WITH_ANOMALY_POINTS),
  },
]
